from .account_settings import AccountSettings
from .course_creation import CourseCreation
from .dashboard_admin import DashboardAdmin
from .dashboard_instructor import DashboardInstructor
from .dashboard_ta import DashboardTA
from .home import Home
from .login import Login
from .section_management import SectionManagement
from .ta_assignments import TAAssignments
from .user_creation import UserCreation
from .user_management import UserManagement
