# Generated by Django 4.2 on 2023-04-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('COURSE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('COURSE_NUMBER', models.IntegerField()),
                ('COURSE_NAME', models.CharField(max_length=255)),
                ('COURSE_DESCRIPTION', models.TextField()),
                ('SEMESTER', models.CharField(max_length=255)),
                ('PREREQUISITES', models.CharField(max_length=255)),
                ('DEPARTMENT', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('SECTION_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SECTION_NUMBER', models.IntegerField()),
                ('SECTION_TYPE', models.CharField(choices=[('LAB', 'Lab'), ('LECTURE', 'Lecture')], max_length=10)),
                ('BUILDING', models.CharField(max_length=255)),
                ('ROOM_NUMBER', models.CharField(max_length=10)),
                ('SECTION_START', models.TimeField()),
                ('SECTION_END', models.TimeField()),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduling_App.course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('USER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('USER_TYPE', models.CharField(choices=[('ADMIN', 'Admin'), ('INSTRUCTOR', 'Instructor'), ('TA', 'Teaching Assistant')], max_length=10)),
                ('FIRST_NAME', models.CharField(max_length=255)),
                ('LAST_NAME', models.CharField(max_length=255)),
                ('EMAIL', models.EmailField(max_length=254, unique=True)),
                ('PASSWORD_HASH', models.CharField(max_length=255)),
                ('PHONE_NUMBER', models.CharField(max_length=20)),
                ('ADDRESS', models.CharField(max_length=255)),
                ('BIRTH_DATE', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TAAssignment',
            fields=[
                ('TA_ASSIGNMENT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('IS_GRADER', models.BooleanField()),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduling_App.course')),
                ('SECTION', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TA_Scheduling_App.section')),
                ('TA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduling_App.user')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='INSTRUCTOR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TA_Scheduling_App.user'),
        ),
    ]
